FROM zokrates/zokrates

USER root

RUN apt update && apt install -y python3 python3-pip

# 你也可以添加 requirements.txt 或其他 Python 包
# RUN pip3 install -r /path/to/your/requirements.txt

USER zokrates
